/* PROJECTS */
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_ERROR = 'FETCH_PROJECTS_ERROR';
export const ADD_PROJECT = 'ADD_PROJECT';
export const SET_NEW_PROJECT = 'SET_NEW_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const SET_EDIT_DATA = 'EDIT_DATA';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const IS_LOADING = 'IS_LOADING';
export const PROJECT_NEXT_PAGE = 'ADD_PROJECT_NEXT_PAGE';
export const ADD_PROJECT_NEXT_PAGE_SUCCESS = 'ADD_PROJECT_NEXT_PAGE_SUCCESS';
export const IS_LOADING_LOAD_MORE = 'IS_LOADING_LOAD_MORE';
export const CLEAR_DATA_PROJECT = 'CLEAR_DATA_PROJECT';
export const SET_PROJECT_STATUS = 'SET_PROJECT_STATUS';
export const SET_DELETE_STATUS = 'SET_DELETE_STATUS';
export const ADD_PROJECT_STATUS = 'ADD_PROJECT_STATUS';


